import { Car, BookingExtra } from './types';

export const LOCATIONS = [
  "New York, JFK Airport",
  "Los Angeles, LAX Airport",
  "Miami, Downtown",
  "San Francisco, Union Square",
  "Chicago, O'Hare Airport",
  "Seattle, Sea-Tac Airport"
];

export const EXCHANGE_RATE = 3.67; // 1 USD = 3.67 AED

export const UI_TRANSLATIONS = {
  en: {
    nav_fleet: "Fleet",
    nav_services: "Services",
    nav_experience: "Experience",
    nav_contact: "Contact",
    nav_admin: "Admin Portal",
    sign_in: "Sign In",
    sign_up: "Register",
    sign_out: "Sign Out",
    profile_link: "Profile",
    hero_badge: "Premium Fleet 2024",
    hero_title_1: "Drive the",
    hero_title_2: "Extraordinary.",
    hero_subtitle: "Experience the perfect blend of performance and luxury. Your journey begins with the perfect vehicle.",
    search_placeholder: "Find your dream car...",
    search_placeholder_short: "Search models...",
    browse_btn: "Browse Fleet",
    collection_title: "Our Collection",
    collection_subtitle: "Find your perfect drive.",
    clear_filters: "Clear Filters",
    no_cars: "No vehicles found",
    no_cars_sub: "Try adjusting your filters or search query.",
    reset_filters: "Reset all filters",
    daily_rate: "Daily Rate",
    ai_pick: "AI Pick",
    specs: "Vehicle Specifications",
    features: "Premium Features",
    rental_conditions: "Rental Conditions",
    book_whatsapp: "WhatsApp Request",
    total_estimate: "Total Estimate",
    back_fleet: "Back to Fleet",
    secure_flexible: "Secure & Flexible",
    cancellation_policy: "Free cancellation up to 24h",
    duration: "Duration",
    dates: "Dates",
    start: "Start",
    end: "End",
    mileage: "Mileage Limit",
    deposit: "Security Deposit",
    insurance: "Insurance",
    engine: "Engine",
    power: "Power",
    acceleration: "0-60 mph",
    max_speed: "Max Speed",
    seats: "Seats",
    auto: "Auto",
    manual: "Manual",
    // Status
    status_available: "Available",
    status_booked: "Booked",
    // Trust Section
    trust_title_1: "Comprehensive Coverage",
    trust_desc_1: "Drive with confidence knowing you're fully covered. Our zero-deductible plans ensure peace of mind.",
    trust_title_2: "Premium Condition",
    trust_desc_2: "Every vehicle is meticulously detailed and inspected before delivery to ensure a showroom experience.",
    trust_title_3: "24/7 Concierge",
    trust_desc_3: "More than just support. Our dedicated team is available round-the-clock for your every need.",
    // Footer
    footer_company: "Company",
    footer_about: "About Us",
    footer_careers: "Careers",
    footer_blog: "Blog",
    footer_support: "Support",
    footer_help: "Help Center",
    footer_terms: "Terms of Service",
    footer_privacy: "Privacy Policy",
    footer_newsletter: "Newsletter",
    footer_email_ph: "Email",
    footer_sub_btn: "Subscribe",
    footer_rights: "© 2024 Q Cars Inc. All rights reserved.",
    footer_desc: "Experience the thrill of the drive with our premium fleet and world-class service.",
    // Filters
    filter_all_makes: "All Makes",
    filter_all_types: "All Types",
    filter_all_years: "All Years",
    // Profile
    profile_welcome: "Welcome",
    profile_manage: "Manage your bookings and preferences",
    profile_total_bookings: "Total Bookings",
    profile_active_rentals: "Active Rentals",
    profile_history: "Booking History",
    profile_no_bookings: "No bookings yet",
    profile_start_journey: "Your journey begins with a single click. Start exploring our fleet.",
    profile_id: "ID",
    profile_extras_selected: "Extras selected",
    profile_booked_on: "Booked on",
    // Booking
    booking_duration_title: "Rental Duration",
    booking_days_label: "Number of Days",
    booking_manual_input: "Manual Input",
    booking_pickup: "Pick-up Date",
    booking_dropoff: "Drop-off Date",
    booking_extras_title: "Optional Extras",
    booking_no_extras: "No extras available",
    booking_no_card: "No credit card required. Payment is handled upon car delivery/pickup.",
    booking_summary: "Rental Summary",
    booking_rate_x: "Rate",
    unavailable_badge: "Currently Unavailable",
    special_monthly: "Monthly Special",
    special_weekly: "Weekly Special",
    save_text: "You save"
  },
  ar: {
    nav_fleet: "الأسطول",
    nav_services: "الخدمات",
    nav_experience: "تجارب",
    nav_contact: "اتصل بنا",
    nav_admin: "لوحة التحكم",
    sign_in: "تسجيل الدخول",
    sign_up: "إنشاء حساب",
    sign_out: "تسجيل الخروج",
    profile_link: "الملف الشخصي",
    hero_badge: "أسطول النخبة ٢٠٢٤",
    hero_title_1: "قُد",
    hero_title_2: "الاستثنائي.",
    hero_subtitle: "استمتع بمزيج مثالي من الأداء والفخامة. رحلتك تبدأ بالسيارة المثالية.",
    search_placeholder: "ابحث عن سيارة أحلامك...",
    search_placeholder_short: "ابحث عن الموديلات...",
    browse_btn: "تصفح الأسطول",
    collection_title: "مجموعتنا",
    collection_subtitle: "اعثر على قيادتك المثالية.",
    clear_filters: "مسح الفلاتر",
    no_cars: "لم يتم العثور على مركبات",
    no_cars_sub: "حاول تعديل الفلاتر أو بحثك.",
    reset_filters: "إعادة تعيين الفلاتر",
    daily_rate: "السعر اليومي",
    ai_pick: "خيار الذكاء الاصطناعي",
    specs: "مواصفات المركبة",
    features: "ميزات مميزة",
    rental_conditions: "شروط التأجير",
    book_whatsapp: "طلب عبر واتساب",
    total_estimate: "التقدير الإجمالي",
    back_fleet: "العودة للأسطول",
    secure_flexible: "آمن ومرن",
    cancellation_policy: "إلغاء مجاني حتى ٢٤ ساعة",
    duration: "المدة",
    dates: "التواريخ",
    start: "البدء",
    end: "الانتهاء",
    mileage: "حد الأميال",
    deposit: "مبلغ التأمين",
    insurance: "تأمين",
    engine: "المحرك",
    power: "القوة",
    acceleration: "٠-١٠٠ كم/س",
    max_speed: "السرعة القصوى",
    seats: "مقاعد",
    auto: "أوتوماتيك",
    manual: "يدوي",
    // Status
    status_available: "متاح",
    status_booked: "محجوز",
    // Trust Section
    trust_title_1: "تغطية شاملة",
    trust_desc_1: "قُد بثقة مع العلم أنك مغطى بالكامل. خططنا الخالية من التحمل تضمن راحة البال.",
    trust_title_2: "حالة ممتازة",
    trust_desc_2: "يتم تفصيل وفحص كل مركبة بدقة قبل التسليم لضمان تجربة وكأنها جديدة.",
    trust_title_3: "كونسيرج ٢٤/٧",
    trust_desc_3: "أكثر من مجرد دعم. فريقنا المخصص متاح على مدار الساعة لتلبية جميع احتياجاتك.",
    // Footer
    footer_company: "الشركة",
    footer_about: "من نحن",
    footer_careers: "وظائف",
    footer_blog: "المدونة",
    footer_support: "الدعم",
    footer_help: "مركز المساعدة",
    footer_terms: "شروط الخدمة",
    footer_privacy: "سياسة الخصوصية",
    footer_newsletter: "النشرة البريدية",
    footer_email_ph: "البريد الإلكتروني",
    footer_sub_btn: "اشترك",
    footer_rights: "© ٢٠٢٤ كيو كارز. جميع الحقوق محفوظة.",
    footer_desc: "جرب متعة القيادة مع أسطولنا المتميز وخدمتنا ذات المستوى العالمي.",
    // Filters
    filter_all_makes: "كل الماركات",
    filter_all_types: "كل الأنواع",
    filter_all_years: "كل السنوات",
    // Profile
    profile_welcome: "مرحباً",
    profile_manage: "إدارة حجوزاتك وتفضيلاتك",
    profile_total_bookings: "إجمالي الحجوزات",
    profile_active_rentals: "تأجيرات نشطة",
    profile_history: "سجل الحجوزات",
    profile_no_bookings: "لا توجد حجوزات بعد",
    profile_start_journey: "رحلتك تبدأ بنقرة واحدة. ابدأ استكشاف أسطولنا.",
    profile_id: "المعرف",
    profile_extras_selected: "إضافات مختارة",
    profile_booked_on: "تم الحجز في",
    // Booking
    booking_duration_title: "مدة الإيجار",
    booking_days_label: "عدد الأيام",
    booking_manual_input: "إدخال يدوي",
    booking_pickup: "تاريخ الاستلام",
    booking_dropoff: "تاريخ الإرجاع",
    booking_extras_title: "إضافات اختيارية",
    booking_no_extras: "لا توجد إضافات متاحة",
    booking_no_card: "لا تتطلب بطاقة ائتمان. يتم الدفع عند استلام السيارة.",
    booking_summary: "ملخص الإيجار",
    booking_rate_x: "السعر",
    unavailable_badge: "غير متوفر حالياً",
    special_monthly: "عرض شهري",
    special_weekly: "عرض أسبوعي",
    save_text: "أنت توفر"
  }
};

export const EXTRAS: BookingExtra[] = [
  { 
    id: 'insurance', 
    name: 'Full Coverage Insurance', 
    name_ar: 'تأمين شامل',
    price: 45, 
    description: 'Zero deductible, comprehensive protection.',
    description_ar: 'بدون مبلغ تحمل، حماية شاملة.'
  },
  { 
    id: 'child_seat', 
    name: 'Child Safety Seat', 
    name_ar: 'مقعد أمان للأطفال',
    price: 15, 
    description: 'ECE R44/04 certified for all ages.',
    description_ar: 'معتمد لجميع الأعمار ECE R44/04.'
  },
  { 
    id: 'gps', 
    name: 'GPS Navigation System', 
    name_ar: 'نظام ملاحة GPS',
    price: 12, 
    description: 'Real-time traffic updates and maps.',
    description_ar: 'تحديثات المرور والخرائط في الوقت الفعلي.'
  },
  { 
    id: 'wifi', 
    name: 'Portable Wi-Fi Hotspot', 
    name_ar: 'نقطة اتصال واي فاي محمولة',
    price: 10, 
    description: 'Unlimited 4G LTE data on the go.',
    description_ar: 'بيانات 4G LTE غير محدودة أثناء التنقل.'
  },
  { 
    id: 'driver', 
    name: 'Additional Driver', 
    name_ar: 'سائق إضافي',
    price: 25, 
    description: 'Share the driving responsibilities.',
    description_ar: 'شارك مسؤوليات القيادة.'
  },
];

// Color Mapping for UI
export const CAR_COLORS: Record<string, string> = {
  'Midnight Silver': '#2C3E50',
  'Obsidian Black': '#0F172A',
  'Guards Red': '#DC2626',
  'Alpine White': '#F8FAFC',
  'Chronos Grey': '#64748B',
  'Firenze Red': '#7F1D1D',
  'Celestial Silver': '#94A3B8',
  'Velocity Blue': '#2563EB'
};

export const CARS: Car[] = [
  {
    id: 'c1',
    isAvailable: true,
    brand: 'Tesla',
    brand_ar: 'تسلا',
    name: 'Model S Plaid',
    name_ar: 'موديل S بلايد',
    year: 2024,
    type: 'Electric',
    type_ar: 'كهربائية',
    pricePerDay: 189,
    image: 'https://images.unsplash.com/photo-1536700503339-1e4b06520771?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 
    gallery: [
        'https://images.unsplash.com/photo-1560958089-b8a1929cea89?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1571127236794-81c0bbfe1ce3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1554744512-d6c603f27c54?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80'
    ],
    seats: 5,
    transmission: 'Automatic',
    transmission_ar: 'أوتوماتيك',
    fuel: 'Electric',
    fuel_ar: 'كهرباء',
    color: 'Midnight Silver',
    color_ar: 'فضي ليلي',
    features: ['Autopilot', 'Yoke Steering', 'Premium Audio', 'Gaming Rig', 'Wireless Charging', 'Glass Roof', 'Heated Seats', 'Sentry Mode'],
    features_ar: ['قيادة ذاتية', 'مقود Yoke', 'صوت ممتاز', 'منصة ألعاب', 'شحن لاسلكي', 'سقف زجاجي', 'مقاعد مدفأة', 'وضع الحراسة'],
    description: 'Experience the future of driving with the 2024 Tesla Model S Plaid. Unmatched acceleration and range.',
    description_ar: 'جرب مستقبل القيادة مع تسلا موديل S بلايد 2024. تسارع ومدى لا مثيل لهما.',
    rating: 4.9,
    highlight: '0-60 in 1.99s',
    highlight_ar: '٠-١٠٠ في ١.٩٩ث',
    specs: {
      engine: 'Tri-Motor AWD',
      horsepower: 1020,
      acceleration: '1.99s',
      topSpeed: '200 mph'
    },
    rentalTerms: {
      mileageLimit: '250 km/day',
      mileageLimit_ar: '٢٥٠ كم/يوم',
      deposit: 2000,
      insurance: 'Standard Basic',
      insurance_ar: 'أساسي قياسي'
    }
  },
  {
    id: 'c2',
    isAvailable: true,
    brand: 'Mercedes-Benz',
    brand_ar: 'مرسيدس بنز',
    name: 'G-Class AMG',
    name_ar: 'جي كلاس AMG',
    year: 2024,
    type: 'SUV',
    type_ar: 'دفع رباعي',
    pricePerDay: 350,
    image: 'https://images.unsplash.com/photo-1520050206274-2c545dea0816?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 
    gallery: [
        'https://images.unsplash.com/photo-1601362840469-51e4d8d58785?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1553956543-6c715207127e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1570374922621-c454794fa82a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80'
    ],
    seats: 5,
    transmission: 'Automatic',
    transmission_ar: 'أوتوماتيك',
    fuel: 'Petrol',
    fuel_ar: 'بنزين',
    color: 'Obsidian Black',
    color_ar: 'أسود بركاني',
    features: ['Off-road Capability', 'Massage Seats', 'Burmester 3D Sound', 'Rear Entertainment', 'Nappa Leather', 'Ambient Lighting', 'Diff Locks', 'Sunroof'],
    features_ar: ['قدرات الطرق الوعرة', 'مقاعد تدليك', 'صوت Burmester 3D', 'ترفيه خلفي', 'جلد نابا', 'إضاءة محيطة', 'أقفال تفاضلية', 'فتحة سقف'],
    description: 'The iconic 2024 G-Wagon. Combines rugged off-road capability with absolute luxury.',
    description_ar: 'سيارة G-Wagon الأيقونية لعام 2024. تجمع بين القدرات القوية للطرق الوعرة والفخامة المطلقة.',
    rating: 4.8,
    highlight: 'Off-Road Icon',
    highlight_ar: 'أيقونة الطرق الوعرة',
    specs: {
      engine: '4.0L V8 Biturbo',
      horsepower: 577,
      acceleration: '4.5s',
      topSpeed: '137 mph'
    },
    rentalTerms: {
      mileageLimit: '200 km/day',
      mileageLimit_ar: '٢٠٠ كم/يوم',
      deposit: 3000,
      insurance: 'Premium Included',
      insurance_ar: 'شامل مميز'
    }
  },
  {
    id: 'c3',
    isAvailable: true,
    brand: 'Porsche',
    brand_ar: 'بورش',
    name: '911 Carrera',
    name_ar: '٩١١ كاريرا',
    year: 2023,
    type: 'Sport',
    type_ar: 'رياضية',
    pricePerDay: 420,
    image: 'https://images.unsplash.com/photo-1503376763036-066120622c74?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 
    gallery: [
        'https://images.unsplash.com/photo-1611651101297-302bc0f5010d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1585890784260-e8894df01235?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80'
    ],
    seats: 2,
    transmission: 'Automatic',
    transmission_ar: 'أوتوماتيك',
    fuel: 'Petrol',
    fuel_ar: 'بنزين',
    color: 'Guards Red',
    color_ar: 'أحمر الحرس',
    features: ['Sport Chrono Package', 'Convertible Top', 'Launch Control', 'Bose Surround', 'Sports Exhaust', 'Paddle Shifters', 'Ceramic Brakes', 'Alcantara Wheel'],
    features_ar: ['حزمة كرونو الرياضية', 'سقف قابل للكشف', 'تحكم في الانطلاق', 'صوت Bose', 'عادم رياضي', 'نواقل حركة', 'فرامل سيراميك', 'عجلة ألكانتارا'],
    description: 'The definitive sports car. Precision engineering and timeless design in this 2023 model.',
    description_ar: 'السيارة الرياضية المثالية. هندسة دقيقة وتصميم خالد في طراز 2023.',
    rating: 5.0,
    highlight: 'Track Legend',
    highlight_ar: 'أسطورة الحلبات',
    specs: {
      engine: '3.0L Twin-Turbo Flat-6',
      horsepower: 379,
      acceleration: '4.0s',
      topSpeed: '182 mph'
    },
    rentalTerms: {
      mileageLimit: '150 km/day',
      mileageLimit_ar: '١٥٠ كم/يوم',
      deposit: 2500,
      insurance: 'Standard Basic',
      insurance_ar: 'أساسي قياسي'
    }
  },
  {
    id: 'c4',
    isAvailable: true,
    brand: 'BMW',
    brand_ar: 'بي إم دبليو',
    name: 'X5 M Competition',
    name_ar: 'X5 M كومبتيشن',
    year: 2025,
    type: 'SUV',
    type_ar: 'دفع رباعي',
    pricePerDay: 210,
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 
    gallery: [
        'https://images.unsplash.com/photo-1556189250-72ba95452242?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1607853202273-797f1c22a38e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1580274455191-1c62238fa995?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80'
    ],
    seats: 5,
    transmission: 'Automatic',
    transmission_ar: 'أوتوماتيك',
    fuel: 'Hybrid',
    fuel_ar: 'هجين',
    color: 'Alpine White',
    color_ar: 'أبيض ألبي',
    features: ['M xDrive', 'Laserlight Headlights', 'Gesture Control', 'Sky Lounge Roof', 'Heated Armrests', 'Head-up Display', 'Park Assist Pro', 'Carbon Fiber Trim'],
    features_ar: ['نظام M xDrive', 'مصابيح ليزر', 'تحكم بالإيماءات', 'سقف سكاي لاونج', 'مساند أذرع مدفأة', 'عرض على الزجاج', 'مساعد ركن', 'ألياف الكربون'],
    description: 'A 2025 high-performance SUV that refuses to compromise on comfort or speed.',
    description_ar: 'سيارة دفع رباعي عالية الأداء لعام 2025 ترفض المساومة على الراحة أو السرعة.',
    rating: 4.7,
    highlight: 'Hybrid Power',
    highlight_ar: 'قوة هجينة',
    specs: {
      engine: '4.4L V8 Hybrid',
      horsepower: 617,
      acceleration: '3.7s',
      topSpeed: '177 mph'
    },
    rentalTerms: {
      mileageLimit: '300 km/day',
      mileageLimit_ar: '٣٠٠ كم/يوم',
      deposit: 1500,
      insurance: 'Standard Basic',
      insurance_ar: 'أساسي قياسي'
    }
  },
  {
    id: 'c5',
    isAvailable: true,
    brand: 'Audi',
    brand_ar: 'أودي',
    name: 'A6 e-tron',
    name_ar: 'A6 إي-ترون',
    year: 2024,
    type: 'Sedan',
    type_ar: 'سيدان',
    pricePerDay: 145,
    image: 'https://images.unsplash.com/photo-1606152421811-aa911018b54e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 
    gallery: [
        'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1502161254066-6c74afbf07aa?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80'
    ],
    seats: 5,
    transmission: 'Automatic',
    transmission_ar: 'أوتوماتيك',
    fuel: 'Electric',
    fuel_ar: 'كهرباء',
    color: 'Chronos Grey',
    color_ar: 'رمادي كرونوس',
    features: ['Quattro AWD', 'Virtual Cockpit Plus', 'Matrix LED', 'Ambient Lighting', 'Bang & Olufsen Sound', 'Adaptive Cruise', '360 Camera', 'Air Suspension'],
    features_ar: ['دفع رباعي كواترو', 'قمرة قيادة افتراضية', 'ماتريكس LED', 'إضاءة محيطة', 'صوت B&O', 'تثبيت سرعة تكيفي', 'كاميرا 360', 'تعليق هوائي'],
    description: 'Sleek, efficient, and packed with technology. The perfect executive sedan.',
    description_ar: 'أنيقة، فعالة، ومليئة بالتكنولوجيا. السيدان التنفيذية المثالية.',
    rating: 4.6,
    highlight: 'Executive EV',
    highlight_ar: 'EV تنفيذي',
    specs: {
      engine: 'Dual Motor Electric',
      horsepower: 469,
      acceleration: '3.8s',
      topSpeed: '155 mph'
    },
    rentalTerms: {
      mileageLimit: 'Unlimited',
      mileageLimit_ar: 'غير محدود',
      deposit: 1000,
      insurance: 'Standard Basic',
      insurance_ar: 'أساسي قياسي'
    }
  },
  {
    id: 'c6',
    isAvailable: true,
    brand: 'Land Rover',
    brand_ar: 'لاند روفر',
    name: 'Range Rover Sport',
    name_ar: 'رينج روفر سبورت',
    year: 2023,
    type: 'SUV',
    type_ar: 'دفع رباعي',
    pricePerDay: 280,
    image: 'https://images.unsplash.com/photo-1563720223185-11003d516935?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 
    gallery: [
        'https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1623877969854-3c66f91f37b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1609520505218-7421da4c3c7c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80'
    ],
    seats: 7,
    transmission: 'Automatic',
    transmission_ar: 'أوتوماتيك',
    fuel: 'Diesel',
    fuel_ar: 'ديزل',
    color: 'Firenze Red',
    color_ar: 'أحمر فيرنز',
    features: ['7 Seats', 'Electronic Air Suspension', 'Meridian Sound System', 'Pivi Pro Infotainment', 'Cooler Box', 'Wade Sensing', 'Soft Close Doors', 'Panoramic Roof'],
    features_ar: ['٧ مقاعد', 'تعليق هوائي إلكتروني', 'صوت ميريديان', 'نظام Pivi Pro', 'صندوق تبريد', 'استشعار عمق الماء', 'أبواب شفط', 'سقف بانورامي'],
    description: 'Perfect for family trips where style and space are paramount.',
    description_ar: 'مثالية للرحلات العائلية حيث الأناقة والمساحة هي الأهم.',
    rating: 4.7,
    highlight: 'Ultimate Luxury SUV',
    highlight_ar: 'قمة فخامة الـSUV',
    specs: {
      engine: '3.0L I6 Turbo Diesel',
      horsepower: 345,
      acceleration: '5.9s',
      topSpeed: '145 mph'
    },
    rentalTerms: {
      mileageLimit: '250 km/day',
      mileageLimit_ar: '٢٥٠ كم/يوم',
      deposit: 1500,
      insurance: 'Standard Basic',
      insurance_ar: 'أساسي قياسي'
    }
  },
  {
    id: 'c7',
    isAvailable: true,
    brand: 'Toyota',
    brand_ar: 'تويوتا',
    name: 'Camry Hybrid',
    name_ar: 'كامري هايبرد',
    year: 2023,
    type: 'Sedan',
    type_ar: 'سيدان',
    pricePerDay: 65,
    image: 'https://images.unsplash.com/photo-1621007947382-bb3c3968e3bb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 
    gallery: [
        'https://images.unsplash.com/photo-1595996956667-27a3c31828f7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1590362891991-f776e747a588?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1589139850116-3e0474026330?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80'
    ],
    seats: 5,
    transmission: 'Automatic',
    transmission_ar: 'أوتوماتيك',
    fuel: 'Hybrid',
    fuel_ar: 'هجين',
    color: 'Celestial Silver',
    color_ar: 'فضي سماوي',
    features: ['Economic Drive Mode', 'Apple CarPlay', 'Toyota Safety Sense', 'Spacious Trunk', 'Wireless Charging', 'Dual Zone Climate', 'Leather Trim', 'Lane Trace Assist'],
    features_ar: ['وضع توفير', 'Apple CarPlay', 'أمان تويوتا', 'صندوق واسع', 'شحن لاسلكي', 'تكييف مزدوج', 'زخارف جلدية', 'تتبع المسار'],
    description: 'Reliable, efficient, and comfortable. The smart choice for long drives.',
    description_ar: 'موثوقة، فعالة، ومريحة. الخيار الذكي للرحلات الطويلة.',
    rating: 4.5,
    highlight: 'Top Efficiency',
    highlight_ar: 'أعلى كفاءة',
    specs: {
      engine: '2.5L 4-Cyl Hybrid',
      horsepower: 208,
      acceleration: '7.4s',
      topSpeed: '112 mph'
    },
    rentalTerms: {
      mileageLimit: 'Unlimited',
      mileageLimit_ar: 'غير محدود',
      deposit: 500,
      insurance: 'Standard Basic',
      insurance_ar: 'أساسي قياسي'
    }
  },
  {
    id: 'c8',
    isAvailable: true,
    brand: 'Ford',
    brand_ar: 'فورد',
    name: 'Mustang GT',
    name_ar: 'موستانج GT',
    year: 2024,
    type: 'Sport',
    type_ar: 'رياضية',
    pricePerDay: 130,
    image: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 
    gallery: [
        'https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80'
    ],
    seats: 4,
    transmission: 'Manual',
    transmission_ar: 'يدوي',
    fuel: 'Petrol',
    fuel_ar: 'بنزين',
    color: 'Velocity Blue',
    color_ar: 'أزرق السرعة',
    features: ['5.0L V8 Coyote', 'Active Valve Exhaust', 'Track Apps', 'Recaro Bucket Seats', 'Brembo Brakes', 'Sync 4 Technology', 'Line Lock', 'MagnaRide'],
    features_ar: ['محرك 5.0L V8', 'عادم نشط', 'تطبيقات الحلبة', 'مقاعد ريكارو', 'فرامل بريمبو', 'تقنية Sync 4', 'قفل الخط', 'تعليق ماجنا'],
    description: 'American muscle at its finest. Feel the roar of the V8.',
    description_ar: 'العضلات الأمريكية في أبهى صورها. اشعر بهدير الـ V8.',
    rating: 4.6,
    highlight: 'V8 Muscle',
    highlight_ar: 'عضلات V8',
    specs: {
      engine: '5.0L Ti-VCT V8',
      horsepower: 480,
      acceleration: '4.3s',
      topSpeed: '155 mph'
    },
    rentalTerms: {
      mileageLimit: '250 km/day',
      mileageLimit_ar: '٢٥٠ كم/يوم',
      deposit: 1000,
      insurance: 'Standard Basic',
      insurance_ar: 'أساسي قياسي'
    }
  }
];

export const SYSTEM_INSTRUCTION = `
You are the AI Concierge for Q Cars, a premium car rental service.
Your goal is to help users find the perfect car from our specific inventory.
You must be helpful, professional, and concise.

Our Inventory (JSON):
${JSON.stringify(CARS.map(c => ({ id: c.id, name: c.name, brand: c.brand, year: c.year, type: c.type, price: c.pricePerDay, features: c.features, color: c.color, highlight: c.highlight })))}

When a user asks for a recommendation, you MUST analyze their request and match it to our inventory.
You MUST return the response in a specific JSON structure containing 'recommendedCarIds' (array of strings) and a 'message' (string).
The 'message' should explain why you picked those cars.

If the user request is unrelated to cars or rentals, politely steer them back to Q Cars services, returning an empty array for IDs.
`;